# Presentation-only cleanup (2026-10-07): replaces stale/internal-sounding CHAMBER-FACING recommendation_note text on candidates that now
# have a proposed body. Writes only destination_item_candidates.recommendation_note. Internal research_notes / sources / needs_confirmation untouched.
N = {  # place_name -> new Chamber-facing note (why CheckOff recommends Discuss + the remaining local question)
 '1764 Vineyards (Pearce)':"Pearce-area winery and a Willcox Wine Country partner. Discuss because it sits outside Willcox town: does it fit the Willcox Hub, and can visitors taste there?",
 "Adolfo's Taco Shop":"Casual taco spot on Rex Allen Dr. Discuss until membership is confirmed and we know the dish locals order most.",
 'Amarillo by Morning':"Western shop on Railroad Avenue. Discuss until membership is confirmed and we know what visitors actually pick up there.",
 'Amerind Texas Canyon Trail Run':"Trail-race event. Discuss because we need the organizer and the date first, and it would only be active around the event.",
 'Antojitos El Cholo Food Truck':"Food truck on Rex Allen Dr. Discuss until membership is confirmed and we know where and when it serves.",
 "Bear's Vintage Thrift":"Thrift store on North Haskell. Discuss until membership and visitor fit are confirmed.",
 'Boulderdash Trail Run':"Trail-race event. Discuss because we need the organizer and the date first, and it would only be active around the event.",
 'Buffalo Sisters':"Trading post on Railroad Avenue. Discuss until membership is confirmed and we know what it is best known for.",
 'Carlson Creek Vineyard':"Willcox Wine Country partner. Discuss because the tasting room address is unclear: where do visitors go, and when?",
 'Cross (+) 8 Cast Iron Cottage Creations':"Local maker and Chamber member. Discuss because we need to know what visitors can buy or see, and where.",
 'Desert Brew':"Coffee stop on North Haskell. Discuss until membership is confirmed and we know its signature drink.",
 'Double S Steakhouse':"Steakhouse on Rex Allen Dr. Discuss until membership is confirmed and we know its signature dish.",
 'Evermore Coffee':"Chamber member. Discuss because we need to know where visitors can actually find it.",
 'Four Tails Vineyards (Pearce)':"Pearce-area winery. Discuss because it sits outside Willcox town: does it fit the Hub, and how do visitors book a tasting?",
 'Friendly Bookstore':"Bookstore on East Maley Street. Discuss until membership is confirmed and we know what makes it worth a CheckOff.",
 'Historic Schwertner House':"Historic 1880 home. Discuss because we need to know whether visitors can see it, or only view it from the street.",
 "Isabel's South of the Border":"Downtown restaurant. Discuss until membership is confirmed and we know its signature dish, including the fire-roasted salsa.",
 "Katy's Rico Hot Dogs":"Roadside hot dog stand. Discuss because we need its schedule and whether it fits.",
 'Laramita Cellars':"Winery near Willcox. Discuss until membership is confirmed and we know visitor access and hours.",
 'Mini ASSets Farm & Ranch':"Chamber member farm. Discuss because we need to know what visitors can actually do there.",
 'Passion Cellars':"Winery near Willcox. Discuss until membership is confirmed and we know visitor hours.",
 "Peter's Mexican Food":"Downtown Mexican restaurant. Discuss until membership is confirmed and we know its signature dish.",
 'Ron Applegate Saddle Shop':"Chamber member and local maker. Discuss because we need to confirm what the shop does and whether visitors can stop in.",
 'Sandor Vineyards (Pearce)':"Pearce-area winery. Discuss because it sits outside Willcox town: does it fit the Hub, and is it open for tastings?",
 'Studio 128':"Downtown studio on Railroad Avenue. Discuss until we know whether the public can join its workshops.",
 'The Neighborhood Studio (Pilates)':"Pilates studio. Discuss until we know its address, its schedule and whether visitors can book.",
 'Vin-Tage':"Vintage shop in the 1881 Commercial building. Discuss until membership is confirmed and we know what it sells now.",
 'Willcox Traders':"Trading post on South Haskell. Discuss until membership is confirmed and its address is verified.",
 'Zarpara Vineyards':"Vineyard beneath the Dos Cabezas Mountains. Discuss until membership is confirmed and we know visitor hours.",
}
