# Presentation-only (2026-10-07): makes Chamber-facing recommendation_note text membership-neutral. Membership is handled by the
# business-level control, so notes cover visitor fit, geography, access, schedule, seasonality and the hook only.
# Writes ONLY recommendation_note on destination_item_candidates / destination_item_decisions. Internal notes and sources untouched.
CAND = {
 "Adolfo's Taco Shop":"Casual taco spot on Rex Allen Dr. Good everyday candidate. Help us name the dish locals order most.",
 'All The Things':"Local shop. Working CheckOff. Help us sharpen the local hook.",
 'Amarillo by Morning':"Western shop on Railroad Avenue. Good nearby candidate. Help us name what visitors actually pick up there.",
 'Amerind Museum':"Strong museum for history visitors. Roughly 35 miles west, so discuss whether it fits the Willcox Hub.",
 'Antojitos El Cholo Food Truck':"Food truck on Rex Allen Dr. Good candidate. Need its current location and schedule confirmed.",
 "Bear's Vintage Thrift":"Thrift store on North Haskell. Working CheckOff. Discuss whether it belongs in the launch set.",
 'Buffalo Sisters':"Trading post on Railroad Avenue. Good nearby candidate. Help us name what it is best known for.",
 'Copper Horse Vineyard':"Tasting room in the same historic building as Strive (Suite B). Good downtown candidate. Need current hours and signature wine confirmed.",
 'Cross (+) 8 Cast Iron Cottage Creations':"Local maker. Working CheckOff. Help us name what visitors can buy or see, and where.",
 'Desert Brew':"Coffee stop on North Haskell. Good everyday candidate. Help us name its signature drink.",
 'Dos Cabezas Coffee Company':"Coffee stop at 308 S Haskell Ave. Good everyday candidate. Need the roasting detail confirmed before we lean on it.",
 'Double S Steakhouse':"Steakhouse on Rex Allen Dr. Good candidate. Help us name its signature dish.",
 'Evermore Coffee':"Coffee at local events. Working CheckOff. Need to know where visitors can actually find it.",
 'Friendly Bookstore':"Bookstore on East Maley Street. Working CheckOff. Help us sharpen the local hook.",
 'Golden Rule Vineyards':"Good downtown wine candidate. Address now confirmed from the winery's own site.",
 'Inde Motorsports Ranch':"Most unusual experience in the set. Need current visitor-access options confirmed.",
 "Isabel's South of the Border":"Downtown restaurant. Good candidate. Help us name its signature dish, including the fire-roasted salsa.",
 'L&B Farm':"Working farm that offers tours by request. Need to know whether casual visitors are welcome.",
 'Laramita Cellars':"Winery near Willcox. Good candidate. Need current visitor access and hours confirmed.",
 'Lazul Aesthetics & Wellness Med Spa':"Wellness is a stretch for most visitors. Discuss whether it belongs, and what services visitors can book.",
 "Lee's Pecans":"Family farm since 1982 with 12 pecan varieties. Strong experience. Call ahead for hours.",
 "Mack's Bar":"Downtown bar at 116 E Maley St. Good nearby candidate. Need hours and signature order confirmed.",
 'Mini ASSets Farm & Ranch':"Farm and ranch. Working CheckOff. Need to know what visitors can actually do there.",
 'Momster Creations':"Local maker. Working CheckOff. Need to know where visitors can find it.",
 'Olivery Orchards':"Olive oil producer based in San Simon, about 45 miles east. Discuss distance fit and confirm visitor access.",
 'Passion Cellars':"Winery near Willcox with a tasting room that looks into the barrel room. Good candidate. Need visitor hours confirmed.",
 "Peter's Mexican Food":"Downtown Mexican restaurant. Good everyday candidate. Help us name its signature dish.",
 'Pillsbury Wine Company':"Vineyard tasting room near Rhumb Line (6450 S Bennett Pl). Good candidate. Need current hours and access confirmed.",
 'R&R Pizza Express':"Local pizza spot opened in 2023 by Sean and Cindy Chaffey. Good everyday candidate. Need buffet days and hours confirmed.",
 'Rafter M Meats':"Strong local meat shop with its own smokehouse. Open weekdays only, 8 to 4.",
 'Reconnect Farm':"Farm with a store. Need the location and visitor hours confirmed.",
 'Rex Allen Days':"October festival (Oct 1 to 4 this year). Need the organizer and next dates confirmed.",
 'Rex Allen Monday music jam':"Live country music on Monday mornings, 10 to 1. Need the current schedule confirmed.",
 'Rex Allen statue':"Public statue across the street from the museum. Need the exact spot and who looks after it confirmed.",
 'Rhumb Line Harvest Hootenanny':"Festival-day event on Oct 17. Need the time and details confirmed.",
 'Rhumb Line lavender bloom':"Peak bloom is June and July. Strong seasonal experience. Need weekday access confirmed.",
 'Roadrunner Kafe at the KOA':"Campground cafe that is open to the public. Good everyday candidate. Need hours confirmed.",
 'Ron Applegate Saddle Shop':"Local maker. Working CheckOff. Need to confirm what the shop does and whether visitors can stop in.",
 'Soaring Wines':"Willcox Wine Country partner at 180 N Railroad Ave. Good downtown candidate. Need current hours and signature wine confirmed.",
 'Stagecoach Inn':"Inn at 100 W Rex Allen Dr. Lodging-specific CheckOff for guests. Discuss whether to keep it as a Nearby-only item.",
 'The Moore House':"Restored 1919 vacation rental. Lodging-specific CheckOff for guests. Discuss whether lodging belongs.",
 'Tirrito Farm tour':"Strongest agritourism item in the set. Need tour days and booking details confirmed.",
 'Tortilleria La Unica':"Restaurant and tortilleria at 142 N Haskell Ave. Strong local experience.",
 'Twin Lakes birding':"Public birding spot. Need the best access point and parking confirmed.",
 'Vin-Tage':"Vintage shop in the 1881 Commercial building. Good downtown candidate. Help us name what it sells now.",
 'Willcox Art League':"A club that meets monthly, with no gallery. Not a visitor experience.",
 'Willcox Community Center Playground':"Good family candidate. Need casual public use confirmed.",
 'Willcox Flyer Bike Ride':"August event. Need the organizer and next date confirmed.",
 'Willcox Traders':"Trading post on South Haskell. Working CheckOff. Need the address verified.",
 'Willcox West Fest':"April event at the Event Center. Strong seasonal experience. Need next dates confirmed.",
 'Willcox Wine Festival (fall)':"Oct 17 and 18, 11 AM to 5 PM, at Railroad Park. Seasonal.",
 'Willcox Wine Festival (spring)':"April festival. Seasonal. Need next dates confirmed.",
 'Zarpara Vineyards':"Vineyard beneath the Dos Cabezas Mountains. Good candidate. Need visitor hours confirmed.",
}
LIVE = {  # item_id prefix -> note
 '5d15ae43':"Current item is the vineyard estate; a downtown tasting-room item is proposed next to it.",
 '455ed6c5':"Hidden (secret) experience at its downtown tasting room, Suite C of the historic Commercial building.",
 '8a9759d7':"Two more specific Rex Allen items are proposed (Monday music jam, the statue).",
 '84b3ad09':"Strong tasting-room item. Tastings are by appointment.",
 '3c706acd':"Address needs a quick check: City list says 4511 E Robbs Rd, our item says 4718 E Robbs Rd.",
 '21fdc0b2':"Strong item: tasting room in the 1917 Willcox Bank and Trust building. A Willcox Wine Country partner.",
 '02decd89':"Museum covering Chiricahua Apache history from Cochise to Geronimo.",
 'd23154df':"Anchored by Willcox Wine Country. Three-plus tasting rooms within a block.",
 'f590b131':"National Park Service site. Free admission.",
 'e620f063':"National Park Service site. The wildlife angle on the same monument.",
 'c4b020ca':"Inside Chiricahua National Monument.",
 '29270440':"National Park Service site.",
 'daf77fc6':"Great hook (1920 Pullman dining car). Help us pick one signature dish.",
 'd397b765':"Coronado National Forest.",
 'f2c29c3b':"Public wildlife area. Best October to February for sandhill cranes.",
 '7018a16a':"Very short item. Need the food experience confirmed before we rewrite it.",
 '132a829f':"Orchard item is live but bare. A fuller rewrite is proposed, plus separate store and corn maze items.",
 'd981fbdc':"Historic 1936 theater. Strong downtown candidate. Need current programming confirmed.",
 'b07c6c8b':"January event. Off until winter.",
 '814f48c1':"Pioneer Cemetery (454 N 3rd Ave). Public history. Who maintains it is unconfirmed.",
}
