// Pure, dependency-free logic for the recap campaign — no Deno/network/DB
// calls in this file so it can be unit tested with `deno test` in isolation.
// index.ts (the edge function) imports these and supplies the DB/network side.

export type Segment =
  | 'ACTIVE_MONTH'
  | 'FALL_CONTINUATION'
  | 'RETURNING_INACTIVE'
  | 'NEVER_CHECKED_OFF'
  | 'EXCLUDED';

export type Platform = 'ios' | 'android' | string | null | undefined;

export type MetroSource =
  | 'checkoff_history'
  | 'explicit_profile'
  | 'list_history'
  | 'interaction_history'
  | 'unknown';

// ── Calendar month boundaries ────────────────────────────────────────────────
// A recap month such as "2026-09" = 2026-09-01T00:00:00 through 2026-10-01T00:00:00, exclusive
// end, in the app's established convention (UTC-anchored calendar dates —
// same convention the existing RPCs and send-partner-recap already use;
// no new timezone system is introduced here).

export function monthBounds(monthParam: string): { start: string; end: string } {
  const m = /^(\d{4})-(\d{2})$/.exec(monthParam);
  if (!m) throw new Error(`Invalid month "${monthParam}", expected YYYY-MM`);
  const year = Number(m[1]);
  const month = Number(m[2]); // 1-12
  if (month < 1 || month > 12) throw new Error(`Invalid month "${monthParam}"`);
  const start = new Date(Date.UTC(year, month - 1, 1));
  const end = new Date(Date.UTC(year, month, 1));
  const iso = (d: Date) => d.toISOString().slice(0, 10);
  return { start: iso(start), end: iso(end) };
}

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

// '2026-09' -> 'September'. Strict: only YYYY-MM with a real month number is accepted.
export function monthLabelFor(monthParam: string): string {
  const m = /^(\d{4})-(0[1-9]|1[0-2])$/.exec(monthParam);
  if (!m) throw new Error(`Invalid month "${monthParam}", expected YYYY-MM`);
  return MONTH_NAMES[Number(m[2]) - 1];
}

export const MONTH_FORMAT = /^\d{4}-(0[1-9]|1[0-2])$/;

// A recap month is closed once its exclusive end date has arrived (UTC).
export function isMonthClosed(monthParam: string, now: Date = new Date()): boolean {
  const { end } = monthBounds(monthParam);
  return now.getTime() >= new Date(`${end}T00:00:00Z`).getTime();
}

// ── Next-metro-vote city input validation ───────────────────────────────────
// Used by campaign-link's POST handler. Deliberately conservative: a real
// city name never needs angle brackets, so rejecting them outright (rather
// than only escaping at render time) is a simple, testable "no executable
// HTML" guarantee in addition to the escapeHtml() defense-in-depth at
// render time.

export const MAX_CITY_LENGTH = 80;

export type CityValidationResult =
  | { ok: true; city: string }
  | { ok: false; reason: 'empty' | 'too_long' | 'unsafe_characters' };

export function validateCityInput(raw: string | null | undefined): CityValidationResult {
  const trimmed = (raw ?? '').trim().replace(/\s+/g, ' ');
  if (!trimmed) return { ok: false, reason: 'empty' };
  if (trimmed.length > MAX_CITY_LENGTH) return { ok: false, reason: 'too_long' };
  if (/[<>]/.test(trimmed)) return { ok: false, reason: 'unsafe_characters' };
  return { ok: true, city: trimmed };
}

// ── Destination safety (open-redirect prevention) ───────────────────────────
// Every dest a campaign email link can carry is either a checkoff:// deep
// link or an https://getcheckoff.com (sub)path — nothing else is ever
// generated by send-recap-campaign. Anything else (a tampered/forged query
// param) falls back to a known-safe default rather than being followed.

export const CAMPAIGN_LINK_FALLBACK_DEST = 'https://getcheckoff.com/download';
export const SITE_URL = 'https://getcheckoff.com';

const SAFE_HTTPS_HOSTS = new Set(['getcheckoff.com', 'apps.apple.com', 'play.google.com', 'www.instagram.com']);

export function isSafeDestination(raw: string): boolean {
  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    return false;
  }
  if (parsed.protocol === 'checkoff:') return true;
  if (parsed.protocol === 'https:' && (SAFE_HTTPS_HOSTS.has(parsed.hostname) || parsed.hostname.endsWith('.getcheckoff.com'))) return true;
  return false;
}

export function safeDestination(raw: string | null | undefined): string {
  const candidate = raw || CAMPAIGN_LINK_FALLBACK_DEST;
  return isSafeDestination(candidate) ? candidate : CAMPAIGN_LINK_FALLBACK_DEST;
}

// ── Deep-link classification + browser-safe translation ─────────────────────
// Every already-delivered campaign email (Sept 1 send, 105 recipients) has
// checkoff://... baked into its signed campaign-link URLs. A raw checkoff://
// redirect target does nothing useful in a browser/email client with no
// handler for that scheme — this is the root cause behind "buttons that
// silently do nothing." classifyDestination() identifies what a dest
// (old checkoff:// or already-https) actually points at, for both
// attribution metadata and translation; translateDeepLinkForBrowser() maps
// it to a real getcheckoff.com page that is guaranteed to render something
// useful in a browser, with an explicit (not automatic) attempt to open the
// app from there.
//
// Route choices deliberately mirror the app's own existing React Navigation
// linking config (App.jsx `linking.config.screens...`), which already
// treats 'list' + '?id=' as a valid path for both checkoff:// and
// https://getcheckoff.com — so /list?id=<uuid> is not a new invented route,
// it is the app's own existing route, just reached over https instead of a
// custom scheme. There is no equivalent 'item' route wired in the app today
// (checkoff://item?id=... has never actually opened anything in the app,
// checkoff:// or not — a separate, pre-existing gap, not introduced by this
// campaign) — /item?id=<uuid> is a forward-compatible placeholder: it works
// today only as a browser fallback, and will start resolving as a real
// in-app deep link with zero further email/link changes whenever the app
// gains that route.

export type DestinationType = 'list' | 'item' | 'home' | 'join' | 'https_other' | 'unknown';

export function classifyDestination(raw: string): { type: DestinationType; id: string | null } {
  let parsed: URL;
  try {
    parsed = new URL(raw);
  } catch {
    return { type: 'unknown', id: null };
  }
  if (parsed.protocol === 'checkoff:') {
    const path = parsed.hostname; // checkoff://list?id=x -> hostname 'list'
    const id = parsed.searchParams.get('id');
    if (path === 'list') return { type: 'list', id };
    if (path === 'item') return { type: 'item', id };
    if (path === 'home' || path === '') return { type: 'home', id: null };
    return { type: 'unknown', id: null };
  }
  if (parsed.protocol === 'https:') {
    if (parsed.pathname.startsWith('/list')) return { type: 'list', id: parsed.searchParams.get('id') };
    if (parsed.pathname.startsWith('/item')) return { type: 'item', id: parsed.searchParams.get('id') };
    if (parsed.pathname.startsWith('/join')) return { type: 'join', id: null };
    return { type: 'https_other', id: null };
  }
  return { type: 'unknown', id: null };
}

// Event types used for a fallback page's own secondary buttons — these are
// deliberate, explicit, user-initiated actions taken FROM an already-loaded
// real webpage, not an automatic email-click redirect, so a checkoff://
// target is appropriate for these specifically (see file header on why a
// raw checkoff:// redirect straight from an email click is not).
export const FALLBACK_PAGE_ACTION_EVENTS = new Set(['app_open_click', 'appstore_click', 'playstore_click']);

export function translateDeepLinkForBrowser(raw: string): string {
  if (!raw.startsWith('checkoff://')) return raw; // already a real https destination
  const { type, id } = classifyDestination(raw);
  if (type === 'list' && id) return `${SITE_URL}/list?id=${encodeURIComponent(id)}`;
  if (type === 'item' && id) return `${SITE_URL}/item?id=${encodeURIComponent(id)}`;
  return `${SITE_URL}/open`; // home, or any unrecognized checkoff:// path
}

// ── Vote-form URL + legacy-recovery classification ──────────────────────────
// HOTFIX 2026-09-02, part 4: voteFormUrl() previously omitted `ev` from the
// redirect it builds to the static /vote page. The static page's own form
// action is built from its URL's query string, so a real production vote
// (Jerry's wife, delivered link) posted with NO `ev` param at all, and was
// rejected by campaign-link ("POST not supported for this event type")
// before any city validation or DB write — nothing was recorded, and
// nothing on that rejection path logs the request body, so the submitted
// city cannot be recovered. `ev: 'next_metro_vote'` is now always included
// here — the single, exhaustively-tested source of truth for this URL.

export function voteFormUrl(
  userId: string, campaignId: string, token: string, segment: string | null, dest: string, error?: string,
): string {
  const params = new URLSearchParams({ u: userId, c: campaignId, t: token, seg: segment || '', dest, ev: 'next_metro_vote' });
  if (error) params.set('error', error);
  return `${SITE_URL}/vote?${params.toString()}`;
}

export type VotePostEligibility = 'explicit' | 'legacy_recovery' | 'rejected';

// Decides whether a POST is allowed into the vote-submission handler at
// all, from the `ev` query param alone (before any body/token/city
// validation, which happens unconditionally afterward regardless of which
// eligible flow this returns — this function only ever narrows which POSTs
// are even considered, never widens what counts as a valid vote).
// 'explicit'       — ev=next_metro_vote, the normal current-page case.
// 'legacy_recovery' — ev is absent entirely (not just non-matching) — the
//                     tightly-scoped compatibility path for a browser tab
//                     that already had the pre-fix /vote page open, whose
//                     form action was built without ev at all. Still fully
//                     re-validated (token + city) downstream; this alone
//                     never records a vote.
// 'rejected'        — ev is present but set to something else entirely —
//                     genuinely not a vote submission, never accepted.
export function classifyVotePostEligibility(evParam: string | null | undefined): VotePostEligibility {
  if (evParam === 'next_metro_vote') return 'explicit';
  if (!evParam) return 'legacy_recovery';
  return 'rejected';
}

// ── Name handling ────────────────────────────────────────────────────────────

export function firstName(displayName: string | null | undefined): string | null {
  const raw = (displayName || '').trim();
  if (!raw) return null;
  return raw.split(/\s+/)[0];
}

export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

// ── Public copy hygiene ──────────────────────────────────────────────────────
// Public facing copy never uses hyphens or dashes. Template copy is written without them; this
// cleans text that comes from the database (list titles such as "Fall 2026 — Munich Metro", item
// names such as "99-meter") before it is shown. Never applied to URLs.
export function publicText(value: unknown): string {
  return String(value ?? '')
    .replace(/\s*[\u2010-\u2015\u2212]\s*/g, ', ')
    .replace(/\s+-\s+/g, ', ')
    .replace(/-/g, ' ')
    .replace(/\s+/g, ' ')
    .replace(/,\s*,/g, ',')
    .trim();
}

// "Phoenix Metro" -> "Phoenix"; "Amalfi Coast" stays as is.
export function cityDisplayName(metroName: string | null | undefined): string {
  return (metroName || '').replace(/\s*Metro$/i, '').trim();
}

// "Fall 2026 — Munich Metro" or "Denver Fall 2026" -> "Fall 2026 in Munich" / "Fall 2026 in Denver".
export function seasonDisplayName(seasonName: string | null | undefined, metroName: string | null | undefined): string {
  const year = /Fall\s*(20\d\d)/i.exec(seasonName || '')?.[1];
  const city = cityDisplayName(metroName);
  if (year && city) return `Fall ${year} in ${city}`;
  if (year) return `Fall ${year}`;
  return publicText(seasonName) || 'your Fall list';
}

// ── Subject lines ────────────────────────────────────────────────────────────
// Month neutral: the month name always comes from the explicit campaign month. Falls back to the
// plain no name subject whenever first_name is missing. No hyphens or dashes.

export type SubjectContext = { monthLabel: string; metroKnown?: boolean; liveCityCount?: number | null };

export function subjectFor(segment: Segment, displayName: string | null | undefined, ctx: SubjectContext): string {
  const name = firstName(displayName);
  switch (segment) {
    case 'ACTIVE_MONTH':
      return name ? `${name}, your ${ctx.monthLabel} CheckOff recap 🍂` : `Your ${ctx.monthLabel} CheckOff recap 🍂`;
    case 'FALL_CONTINUATION':
      return name ? `${name}, your Fall list is waiting 🍂` : 'Your Fall list is waiting 🍂';
    case 'RETURNING_INACTIVE':
      return 'A lot is new on CheckOff since you last visited';
    case 'NEVER_CHECKED_OFF':
      if (ctx.metroKnown !== false) return 'Your first CheckOff is waiting';
      return ctx.liveCityCount ? `CheckOff is now live in ${ctx.liveCityCount} metros` : 'See where CheckOff is live';
    default:
      return `Your ${ctx.monthLabel} CheckOff recap`;
  }
}

// Test send subjects are always prefixed so they are unmistakable in an inbox.
export const TEST_SEND_LABELS: Record<string, string> = {
  ACTIVE_MONTH: '[TEST ACTIVE]',
  FALL_CONTINUATION: '[TEST FALL]',
  RETURNING_INACTIVE: '[TEST RETURNING]',
  NEVER_CHECKED_OFF: '[TEST NEW USER]',
  NEVER_CHECKED_OFF_UNKNOWN: '[TEST NEW USER NO CITY]',
};

export function testSendSubject(variantKey: string, baseSubject: string): string {
  return `${TEST_SEND_LABELS[variantKey] || '[TEST]'} ${baseSubject}`;
}

export function previewTextFor(segment: Segment, ctx: SubjectContext): string {
  switch (segment) {
    case 'ACTIVE_MONTH': return `See what you checked off in ${ctx.monthLabel}, plus new places to explore.`;
    case 'FALL_CONTINUATION': return 'Pick up where you left off and keep going.';
    case 'RETURNING_INACTIVE': return 'New cities and places are waiting. Update CheckOff and come back.';
    case 'NEVER_CHECKED_OFF':
      return ctx.metroKnown !== false ? 'A few great places to start your first CheckOff.' : 'Choose a city and make your first CheckOff.';
    default: return `Your ${ctx.monthLabel} CheckOff recap.`;
  }
}

// ── Countdown ─────────────────────────────────────────────────────────────────

export function daysRemaining(endDateIso: string | null | undefined, nowIso?: string): number | null {
  if (!endDateIso) return null;
  const now = nowIso ? new Date(nowIso) : new Date();
  const end = new Date(endDateIso);
  if (Number.isNaN(end.getTime())) return null;
  const nowUTC = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const endUTC = Date.UTC(end.getUTCFullYear(), end.getUTCMonth(), end.getUTCDate());
  const diff = Math.round((endUTC - nowUTC) / 86400000);
  return Math.max(diff, 0);
}

// ── Device CTA ────────────────────────────────────────────────────────────────

const APP_STORE_URL = 'https://apps.apple.com/us/app/checkoff/id6762678030';
const PLAY_STORE_URL = 'https://play.google.com/store/apps/details?id=com.getcheckoff.app';
const UNIVERSAL_DOWNLOAD_URL = 'https://getcheckoff.com/download';

export function deviceCta(platform: Platform): { label: string; url: string } {
  const p = (platform || '').toLowerCase();
  if (p === 'ios') return { label: 'Open CheckOff', url: 'checkoff://home' };
  if (p === 'android') return { label: 'Open CheckOff', url: 'checkoff://home' };
  return { label: 'Open CheckOff', url: UNIVERSAL_DOWNLOAD_URL };
}

export function storeCta(platform: Platform): { label: string; url: string } {
  const p = (platform || '').toLowerCase();
  if (p === 'ios') return { label: 'Get it on the App Store', url: APP_STORE_URL };
  if (p === 'android') return { label: 'Get it on Google Play', url: PLAY_STORE_URL };
  return { label: 'Download CheckOff', url: UNIVERSAL_DOWNLOAD_URL };
}

// ── Streak messaging ─────────────────────────────────────────────────────────
// Weekly streak only (matches users.current_streak semantics — never framed
// as a daily streak). currentStreakWeeks is whatever users.current_streak
// holds; hasRecentActivity should be true if the user has any check-in within
// roughly the last 2 weeks (recap builder passes this in from the DB row).

export function streakMessage(currentStreakWeeks: number | null | undefined, hasRecentActivity: boolean): string {
  const weeks = currentStreakWeeks || 0;
  if (weeks >= 1) {
    return `Your streak is ${weeks} ${weeks === 1 ? 'week' : 'weeks'} strong. Keep it going this weekend.`;
  }
  if (hasRecentActivity) {
    return "You're building momentum. Check off something this week to keep it going.";
  }
  return 'Your next streak starts with one CheckOff.';
}

// ── Almost-there / bonus-unlock messaging ───────────────────────────────────
// Never invents a threshold — only surfaces one when the caller supplies a
// real unlock_threshold from list_items and the user is genuinely close.

export function almostThereMessage(
  checkedCount: number,
  unlockThreshold: number | null | undefined,
): string | null {
  if (!unlockThreshold || unlockThreshold <= 0) return null;
  const remaining = unlockThreshold - checkedCount;
  if (remaining <= 0) return null;
  if (remaining > 3) return null; // "almost there" = genuinely close, not a generic nudge
  const noun = remaining === 1 ? 'CheckOff' : 'CheckOffs';
  return `Just ${remaining} more ${noun} to unlock your next bonus.`;
}

// ── Seasonal closing copy ────────────────────────────────────────────────────
// Neutral by default. A metro only gets its own regional line if one has been deliberately authored
// and verified here. Recent activity in a metro is never proof of where someone lives, and weather
// claims can be wrong when the email is opened, so the map is intentionally empty today.

export const NEUTRAL_CLOSING_COPY = 'Fall is a great time to get out and check something off.';
export const AUTHORED_REGION_COPY: Record<string, string> = {};

// metro_areas.name is usually "<City> Metro" (for example "Phoenix Metro"); this strips the suffix
// to get the bare lowercase city used for curated_lists.city_slug matching.
export function metroSlug(metroName: string | null | undefined): string {
  return (metroName || '').replace(/\s*Metro$/i, '').trim().toLowerCase();
}

export function seasonalClosingCopy(metroName: string | null | undefined): string {
  return AUTHORED_REGION_COPY[metroSlug(metroName)] ?? NEUTRAL_CLOSING_COPY;
}

// ── Recommendation shaping ───────────────────────────────────────────────────
// Gives the (already metro and exclusion filtered) DB recommendation rows three distinct roles.
// Deterministic, no fabricated collaborative filtering claim.

export type RawRecommendation = { id: string; body: string; difficulty?: number | null; popularity?: number; url: string };
export type RoledRecommendation = RawRecommendation & { role: 'easy_next' | 'made_for_you' | 'try_different' };

export function assignRecommendationRoles(items: RawRecommendation[]): RoledRecommendation[] {
  if (!items?.length) return [];
  const sorted = [...items].sort((a, b) => (a.difficulty ?? 99) - (b.difficulty ?? 99));
  const roles: RoledRecommendation['role'][] = ['easy_next', 'made_for_you', 'try_different'];
  return sorted.slice(0, 3).map((it, i) => ({ ...it, role: roles[i] ?? 'made_for_you' }));
}

// Some metros' curated_lists rows are still titled or tagged for a prior season (Phoenix has
// "Summer 2026" lists). Never surface a visibly wrong season title in a Fall recap email.
export function isStaleSeasonTitle(title: string): boolean {
  return /\b(summer|winter|spring)\s*20\d\d\b/i.test(title);
}

export type CuratedListRow = { id: string; title: string; season?: string | null };

// Structural filter (season column) is primary; the title regex is a safety net only.
export function selectThemedLists(rows: CuratedListRow[]): { title: string; id: string }[] {
  const allowedSeasons = new Set(['fall', 'anytime']);
  return rows
    .filter((r) => (r.season == null || allowedSeasons.has(r.season)) && !isStaleSeasonTitle(r.title))
    .slice(0, 3)
    .map((r) => ({ id: r.id, title: r.title }));
}
